'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),os=require('os'),{spawn,spawnSync}=require('child_process');
const G=require('./lib/goldbrain'); loadEnv();
const V='4.0.0',PORT=+process.env.PORT||8080,HOST=process.env.HOST||'127.0.0.1',ROOT=__dirname,D=path.join(ROOT,'data'),R=path.join(ROOT,'runtime');
const U=path.join(D,'user.json'),W=path.join(D,'workers.json'),P=path.join(R,'process.json'),M=path.join(R,'miner.json'),C=path.join(R,'xmrig-config.json'),L=path.join(R,'xmrig.log'),E=path.join(R,'estimator.json');
const MO={commit:'13b87c26ebfb2b9e9c1fb1cf1156856ea5cd2cb0',blob:'fff8cbec64afdad231cb416037b96cee5f56ccf9',ver:'6.26.0-mo4'};
MO.url=`https://raw.githubusercontent.com/MoneroOcean/xmrig_setup/${MO.commit}/xmrig.zip`;
const STOCK={ver:'6.26.0',sha:'bba8097cb37d9b458a1cb1137876b27cde6740d17fe4ccbc086ba07d87d9e147'};STOCK.url=`https://github.com/xmrig/xmrig/releases/download/v${STOCK.ver}/xmrig-${STOCK.ver}-windows-x64.zip`;
const POOL=process.env.POOL_HOST||'gulf.moneroocean.stream',POOLPORT=+process.env.POOL_PORT||20128,SECRET=process.env.WORKER_SHARED_SECRET||'';let child=null,busy=false;
fs.mkdirSync(D,{recursive:true});fs.mkdirSync(R,{recursive:true});
function loadEnv(){const f=path.join(__dirname,'.env');if(!fs.existsSync(f))return;for(const raw of fs.readFileSync(f,'utf8').split(/\r?\n/)){const s=raw.trim(),i=s.indexOf('=');if(!s||s[0]==='#'||i<1)continue;let v=s.slice(i+1).trim();if((v[0]==='"'&&v.at(-1)==='"')||(v[0]==="'"&&v.at(-1)==="'"))v=v.slice(1,-1);if(process.env[s.slice(0,i).trim()]===undefined)process.env[s.slice(0,i).trim()]=v}}
const read=(f,x={})=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return x}},write=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2));
const loop=req=>['127.0.0.1','::1','::ffff:127.0.0.1'].includes(String(req.socket.remoteAddress||''));function local(req){if(!loop(req))throw Object.assign(new Error('Controle local somente.'),{status:403})}
function send(res,s,x){const b=JSON.stringify(x);res.writeHead(s,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(b),'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY'});res.end(b)}
async function body(req){const a=[];let n=0;for await(const c of req){n+=c.length;if(n>1048576)throw Object.assign(new Error('Payload grande'),{status:413});a.push(c)}if(!a.length)return{};try{return JSON.parse(Buffer.concat(a))}catch{throw Object.assign(new Error('JSON inválido'),{status:400})}}
function walletOK(v){return /^[48][1-9A-HJ-NP-Za-km-z]{94}$/.test(String(v||'').trim())||/^4[1-9A-HJ-NP-Za-km-z]{105}$/.test(String(v||'').trim())}
function defaults(){return{wallet:'',electricity:.90,milestoneXmr:.000015,performanceMode:'max',gpuMode:'auto',cpuThreadsPercent:100,basePowerWatts:30,cpuPowerWatts:75,gpuPowerWatts:47,measuredPowerWatts:0}}
function user(){return{...defaults(),...read(U,{})}}function saveUser(b){const o=user(),w=String(b.wallet??o.wallet).trim();if(!walletOK(w))throw Object.assign(new Error('Carteira XMR inválida.'),{status:400});const x={...o,...b,wallet:w,electricity:Math.max(0,+b.electricity||+o.electricity),milestoneXmr:G.clamp(+b.milestoneXmr||o.milestoneXmr,.000001,1),performanceMode:['smart','max'].includes(b.performanceMode)?b.performanceMode:o.performanceMode,gpuMode:['auto','on','off'].includes(b.gpuMode)?b.gpuMode:o.gpuMode,cpuThreadsPercent:G.clamp(+b.cpuThreadsPercent||o.cpuThreadsPercent,25,100),updatedAt:new Date().toISOString()};write(U,x);return x}
const alive=p=>{try{if(!p)return false;process.kill(+p,0);return true}catch{return false}};function find(dir,name){if(!fs.existsSync(dir))return null;for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isFile()&&e.name.toLowerCase()===name)return p;if(e.isDirectory()){const q=find(p,name);if(q)return q}}return null}
async function dl(url,file){const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'IdeaGold/4'},signal:AbortSignal.timeout(120000)});if(!r.ok)throw new Error(`Download ${r.status}`);const b=Buffer.from(await r.arrayBuffer());fs.writeFileSync(file,b);return b}
function unzip(zip,to){fs.rmSync(to,{recursive:true,force:true});fs.mkdirSync(to,{recursive:true});const q=s=>s.replaceAll("'","''"),p=spawnSync('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-Command',`Expand-Archive -LiteralPath '${q(zip)}' -DestinationPath '${q(to)}' -Force`],{encoding:'utf8',windowsHide:true});if(p.status)throw new Error('Falha ao extrair minerador')}
async function install(){if(process.platform!=='win32')throw new Error('Instalação automática local é Windows x64.');const old=read(M,{});if(old.exe&&fs.existsSync(old.exe)&&old.engine==='moneroocean-advanced')return old;try{const z=path.join(R,'mo.zip'),b=await dl(MO.url,z),sha=crypto.createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex');if(sha!==MO.blob)throw new Error('Integridade MoneroOcean inválida');const d=path.join(R,'xmrig-mo'),x=unzip(z,d),exe=find(d,'xmrig.exe'),base=find(d,'config.json');fs.rmSync(z,{force:true});if(!exe)throw new Error('xmrig.exe ausente');const m={engine:'moneroocean-advanced',version:MO.ver,exe,base,verified:true,source:'MoneroOcean/xmrig_setup',commit:MO.commit};write(M,m);return m}catch(e){console.warn('Fallback XMRig:',e.message);const z=path.join(R,'stock.zip'),b=await dl(STOCK.url,z),sha=crypto.createHash('sha256').update(b).digest('hex');if(sha!==STOCK.sha)throw new Error('SHA-256 XMRig inválido');const d=path.join(R,'xmrig-stock');unzip(z,d);fs.rmSync(z,{force:true});const exe=find(d,'xmrig.exe'),base=find(d,'config.json');if(!exe)throw new Error('xmrig.exe ausente');const m={engine:'xmrig-stock',version:STOCK.ver,exe,base,verified:true,source:'xmrig/xmrig'};write(M,m);return m}}
function config(u,m){const b=m.base?read(m.base,{}):{},worker=os.hostname().replace(/\W/g,'_').slice(0,32),cpu={...(b.cpu||{}),enabled:true,'huge-pages':true,'huge-pages-jit':true,'max-threads-hint':u.performanceMode==='max'?100:u.cpuThreadsPercent,yield:false,priority:3,asm:true};return{...b,autosave:false,background:false,colors:false,randomx:{...(b.randomx||{}),mode:'fast',rdmsr:true,wrmsr:true,numa:true,'scratchpad-prefetch-mode':1},cpu,opencl:{...(b.opencl||{}),enabled:u.gpuMode!=='off',cache:true,adl:true},cuda:{...(b.cuda||{}),enabled:false},pools:[{...(b.pools?.[0]||{}),url:`${POOL}:${POOLPORT}`,user:u.wallet,pass:`IdeaGold-${worker}`,'rig-id':worker,tls:true,keepalive:true,enabled:true}],http:{enabled:true,host:'127.0.0.1',port:18080,restricted:true},'donate-level':1,'print-time':10,'health-print-time':30,'pause-on-battery':true,'log-file':L}}
async function start(){const u=user();if(!walletOK(u.wallet))throw new Error('Salve sua carteira XMR.');let m=read(M,{});if(!m.exe||!fs.existsSync(m.exe))m=await install();const p=read(P,{});if(alive(p.pid))return{alreadyRunning:true,pid:p.pid};write(C,config(u,m));const out=fs.openSync(L,'a');child=spawn(m.exe,['-c',C],{cwd:path.dirname(m.exe),stdio:['ignore',out,out],windowsHide:true});write(P,{pid:child.pid,desiredRunning:true,restarts:p.restarts||0,startedAt:new Date().toISOString()});child.on('exit',code=>{const x=read(P,{});x.stoppedAt=new Date().toISOString();x.exitCode=code;write(P,x);child=null});return{started:true,pid:child.pid,engine:m.engine}}
function stop(){const p=read(P,{});p.desiredRunning=false;if(alive(p.pid))spawnSync('taskkill',['/PID',String(p.pid),'/T','/F'],{windowsHide:true});write(P,p);child=null;return{stopped:true}}
async function restart(){const p=read(P,{});if(alive(p.pid))spawnSync('taskkill',['/PID',String(p.pid),'/T','/F'],{windowsHide:true});await new Promise(r=>setTimeout(r,800));return start()}
async function xapi(ep){try{const r=await fetch(`http://127.0.0.1:18080${ep}`,{signal:AbortSignal.timeout(1800)});return r.ok?await r.json():null}catch{return null}}
function poolMap(d){const pick=(...k)=>{for(const x of k)if(d?.[x]!=null)return +d[x]||0;return 0};return d?{hashrate:pick('hash','hash2','hashrate'),dueXmr:pick('amtDue','balance')/1e12,paidXmr:pick('amtPaid','paid')/1e12,validShares:pick('validShares'),invalidShares:pick('invalidShares')}:null}
async function pool(wallet){if(!walletOK(wallet))return null;try{const r=await fetch(`https://api.moneroocean.stream/miner/${encodeURIComponent(wallet)}/stats`,{signal:AbortSignal.timeout(5000)});return r.ok?poolMap(await r.json()):null}catch{return null}}
async function network(){try{const r=await fetch('https://api.moneroocean.stream/network/stats',{signal:AbortSignal.timeout(5000)}),d=await r.json();let reward=+d.value||.6;if(reward>1e6)reward/=1e12;if(!(reward>0&&reward<10))reward=.6;return{difficulty:+d.difficulty||0,reward,height:+d.height||+d.main_height||0}}catch{return null}}
async function market(){try{const r=await fetch('https://api.coingecko.com/api/v3/simple/price?ids=monero&vs_currencies=brl,usd&include_24hr_change=true',{signal:AbortSignal.timeout(7000)});return r.ok?(await r.json()).monero:null}catch{return null}}
function workers(){const st=read(W,{workers:{}}),now=Date.now(),all=Object.values(st.workers||{}).map(x=>({...x,online:now-new Date(x.lastSeen).getTime()<45000})),on=all.filter(x=>x.online);return{workers:all,online:on.length,hashrate:on.reduce((a,x)=>a+(+x.hashrate||0),0),powerWatts:on.reduce((a,x)=>a+(+x.powerWatts||0),0),cloudCostBrlDay:on.reduce((a,x)=>a+(+x.cloudCostBrlDay||0),0)}}
function verify(req,raw){if(!SECRET||SECRET==='troque-por-um-segredo-forte')return false;const t=String(req.headers['x-ideagold-timestamp']||''),s=String(req.headers['x-ideagold-signature']||'');if(!/^\d{10,16}$/.test(t)||!/^[a-f0-9]{64}$/i.test(s)||Math.abs(Date.now()-+t)>300000)return false;const e=crypto.createHmac('sha256',SECRET).update(t).update('.').update(raw).digest('hex');return crypto.timingSafeEqual(Buffer.from(s,'hex'),Buffer.from(e,'hex'))}
function sample(row){const s=read(E,{samples:[]});if(!s.samples.length||row.ts-s.samples.at(-1).ts>20000)s.samples.push(row);s.samples=s.samples.filter(x=>Date.now()-x.ts<172800000).slice(-3000);write(E,s);return s.samples}
async function status(req){const u=user(),m=read(M,{}),p=read(P,{}),wk=workers();const [sum,backs,ps,net,mkt]=await Promise.all([xapi('/2/summary'),xapi('/2/backends'),pool(u.wallet),network(),market()]);const running=!!sum||alive(p.pid),h=+sum?.hashrate?.total?.[0]||0,ph=+ps?.hashrate||0,total=+(ps?.dueXmr||0)+ +(ps?.paidXmr||0),eff=ph||h+wk.hashrate,rows=walletOK(u.wallet)?sample({ts:Date.now(),totalEarnedXmr:total,effectiveHashrate:eff}):read(E,{samples:[]}).samples||[];const empirical=G.weightedRegressionRate(rows),poolRate=net&&ph?G.networkXmrRate(ph,net.difficulty,net.reward,.99):0,algo=String(sum?.connection?.algo||'').toLowerCase(),localRate=net&&h&&(!algo||/rx\/0|randomx/.test(algo))?G.networkXmrRate(h,net.difficulty,net.reward,.99):0,hy=G.hybridRateEstimate({empiricalRate:empirical.rate,empiricalConfidence:empirical.confidence,poolRate,poolConfidence:ph?.82:0,localRate,localConfidence:localRate?.45:0}),varh=G.hashVariability(rows),bl=Array.isArray(backs?.backends)?backs.backends:[],gpu=JSON.stringify(bl).toLowerCase().includes('opencl'),watts=running?(+u.measuredPowerWatts||(+u.basePowerWatts+(+u.cpuPowerWatts||75)+(gpu?(+u.gpuPowerWatts||47):0))):0,totalW=watts+wk.powerWatts,proj=G.projectionTable({xmrPerSec:hy.rate,priceBrl:+mkt?.brl||0,electricityBrlKwh:+u.electricity||0,powerWatts:totalW,cloudCostBrlDay:wk.cloudCostBrlDay}),mile=G.nextMilestone({totalEarnedXmr:total,stepXmr:+u.milestoneXmr,xmrPerSec:hy.rate,rateCv:varh.cv}),share=G.shareArrivalEstimate(h,+sum?.connection?.diff||0),risk=G.monteCarloProfit({xmrPerSec:hy.rate,priceBrl:+mkt?.brl||0,electricityBrlKwh:+u.electricity||0,powerWatts:totalW,cloudCostBrlDay:wk.cloudCostBrlDay,simulations:8000,days:30,seed:Math.floor(Date.now()/300000)});return{version:V,configured:walletOK(u.wallet),walletFull:loop(req)?u.wallet:'',settings:u,miner:{installed:!!m.exe,verified:!!m.verified,engine:m.engine,source:m.source,version:m.version,running,pid:p.pid||null,hashrate:h,effectiveHashrate:eff,algo,accepted:+sum?.connection?.accepted||+ps?.validShares||0,rejected:+sum?.connection?.rejected||+ps?.invalidShares||0,pool:sum?.connection?.pool||`${POOL}:${POOLPORT}`,gpuActive:gpu},workers:wk,pool:ps?{...ps,totalEarnedXmr:total}:null,network:net,market:{xmrBRL:+mkt?.brl||0,xmrUSD:+mkt?.usd||0,change24h:+mkt?.brl_24h_change||0},estimator:{xmrPerSecond:hy.rate,xmrPerHour:hy.rate*3600,confidence:hy.confidence,sources:hy.sources,milestone:mile,shareEta:share},profit:{...proj,powerWatts:totalW,cloudCostBrlDay:wk.cloudCostBrlDay,risk}}}
function staticFile(res,p){const file=p==='/'||p==='/index.html'?'index-v4.html':null;if(!file)return false;const b=fs.readFileSync(path.join(ROOT,file));res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-length':b.length,'cache-control':'no-cache'});res.end(b);return true}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&staticFile(res,url.pathname))return;if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{ok:true,name:'IdeaGold GoldBrain',version:V});if(req.method==='GET'&&url.pathname==='/api/simple/status')return send(res,200,await status(req));if(req.method==='GET'&&url.pathname==='/api/workers'){local(req);return send(res,200,workers())}if(req.method==='POST'&&url.pathname==='/api/workers/heartbeat'){const a=[];for await(const c of req)a.push(c);const raw=Buffer.concat(a);if(!verify(req,raw))return send(res,401,{error:'assinatura inválida'});const b=JSON.parse(raw),id=String(b.id||'').slice(0,80);if(!/^[\w.-]+$/.test(id))throw new Error('worker inválido');const st=read(W,{workers:{}});st.workers[id]={...b,id,lastSeen:new Date().toISOString()};write(W,st);return send(res,200,{ok:true})}if(req.method==='POST'&&url.pathname.startsWith('/api/simple/')){local(req);const action=url.pathname.split('/').at(-1);if(action==='wallet')return send(res,200,{ok:true,user:saveUser(await body(req))});if(action==='settings'){const b=await body(req),cur=user();return send(res,200,{ok:true,user:saveUser({...cur,...b,wallet:cur.wallet})})}if(action==='install')return send(res,200,{ok:true,miner:await install()});if(action==='start')return send(res,200,{ok:true,result:await start()});if(action==='stop')return send(res,200,{ok:true,result:stop()});if(action==='restart')return send(res,200,{ok:true,result:await restart()})}return send(res,404,{error:'Rota não encontrada'})}catch(e){console.error(e);send(res,e.status||500,{error:e.message||'Erro interno'})}});
async function watch(){if(busy)return;busy=true;try{const p=read(P,{});if(p.desiredRunning&&!alive(p.pid)&&walletOK(user().wallet)){if((p.restarts||0)<8){p.restarts=(p.restarts||0)+1;write(P,p);await start()}}}catch(e){console.error('watchdog',e.message)}finally{busy=false}}setInterval(watch,30000).unref();
server.listen(PORT,HOST,()=>console.log(`\nIdeaGold ${V}: http://${HOST}:${PORT}\nGoldBrain: CPU/GPU auto-switch + estimativa híbrida + workers.`));
