'use strict';
const A=require('./anomaly');const E=require('../lib/efficiency-brain');
class SupremeMind{
  constructor({store,settingsProvider,saveSettings,miner,onEvent}){Object.assign(this,{store,settingsProvider,saveSettings,miner});this.onEvent=onEvent||(()=>{});this.lastDecisionAt=0;this.runtime={state:'observing',lastEvaluation:null,lastDecision:null,anomalies:{},classification:{rules:'Rule Engine',statistics:'Statistical Model',optimizer:'Bayesian Optimizer',anomaly:'Robust Anomaly Detection',machineLearning:'Disabled — insufficient hardware-specific training data'}};}
  status(){const s=this.settingsProvider(),profiles=this.store.profiles(s.fingerprint),safe=this.store.safeProfile(s.fingerprint);return {enabled:Boolean(s.optimization.enabled),mode:s.optimization.mode,autoApply:Boolean(s.optimization.autoApply),state:s.optimization.enabled?this.runtime.state:'disabled',classification:this.runtime.classification,bestProfile:safe,profilesCount:profiles.length,experiments:this.store.benchmarks(s.fingerprint,500).length,lastDecision:this.runtime.lastDecision,anomalies:this.runtime.anomalies,recentDecisions:this.store.decisions(10)};}
  toggle(enabled){const s=this.saveSettings({optimization:{...this.settingsProvider().optimization,enabled:Boolean(enabled)}});this.runtime.state=enabled?'observing':'disabled';this.store.decision({source:'supreme-mind',objective:s.optimization.mode,action:enabled?'enable':'disable',reason:'Alteração explícita do usuário',confidence:1});this.onEvent('supreme-mind',this.status());return this.status();}
  mode(mode){if(!['performance','efficiency','profit','balanced','eco','manual'].includes(mode))throw Object.assign(new Error('Modo Supreme Mind inválido.'),{status:400});const s=this.saveSettings({optimization:{...this.settingsProvider().optimization,mode}});this.store.decision({source:'supreme-mind',objective:mode,action:'mode-change',reason:`Objetivo alterado para ${mode}`,confidence:1});this.onEvent('supreme-mind',this.status());return this.status();}
  async applyProfile(id){const s=this.settingsProvider(),p=this.store.profile(id);if(!p||p.fingerprint!==s.fingerprint)throw Object.assign(new Error('Perfil incompatível com este hardware.'),{status:400});if(!p.safe)throw Object.assign(new Error('Perfil não marcado como seguro.'),{status:400});const before=s.mining;this.saveSettings({mining:{...before,...p.config}});await this.miner.restart(p.config);this.store.decision({source:'supreme-mind',objective:s.optimization.mode,action:'apply-profile',reason:`Perfil seguro ${p.name} aplicado pelo usuário`,before,after:p.config,observed:p.metrics,confidence:p.metrics?.confidence||.8});return p;}
  async restoreSafe(){const s=this.settingsProvider(),p=this.store.safeProfile(s.fingerprint);if(!p)throw Object.assign(new Error('Ainda não existe perfil seguro medido.'),{status:404});return this.applyProfile(p.id);}
  async evaluate(status){const s=this.settingsProvider();if(!s.optimization.enabled)return this.status();const history=this.store.history(60*60_000,360),rejectRate=(status.miner.accepted+status.miner.rejected)>0?status.miner.rejected/(status.miner.accepted+status.miner.rejected):0;const anomalies=A.evaluate({localHash:status.miner.localHash,powerWatts:status.power.watts,cpuTemp:status.hardware.cpuTemperatureC,rejectRate},history);this.runtime.anomalies=anomalies;this.runtime.lastEvaluation=Date.now();const critical=Object.entries(anomalies).find(([,v])=>v.level==='critical');if(critical&&Date.now()-this.lastDecisionAt>5*60_000){this.lastDecisionAt=Date.now();this.runtime.lastDecision={at:Date.now(),action:'safety-observation',reason:`Anomalia crítica: ${critical[0]}`,automaticAction:'none'};this.store.decision({source:'anomaly-detector',objective:s.optimization.mode,action:'warn',reason:this.runtime.lastDecision.reason,confidence:.9});this.store.log('optimization','warn',this.runtime.lastDecision.reason);}
    const profiles=this.store.profiles(s.fingerprint).filter(p=>p.safe),currentProfile=profiles.find(p=>p.config.threads===s.mining.threads),candidates=profiles.map(p=>({id:p.id,current:p.id===currentProfile?.id,hashrate:p.metrics?.hashMedian,powerWatts:p.metrics?.powerMedian,powerMeasured:Boolean(p.metrics?.powerMedian&&s.power.mode==='manual-wattmeter'),netBrlDay:p.metrics?.netDayBrl,accepted:10,rejected:0,stabilityCv:p.metrics?.hashCv||.1}));if(candidates.length>=2){const choice=E.chooseCandidate(candidates,{minImprovementPct:s.optimization.minImprovementPct,maxTempC:s.thermal.criticalC});if(choice.switchRecommended&&choice.winner){this.runtime.lastDecision={at:Date.now(),action:s.optimization.autoApply?'recommend-and-apply':'recommend',reason:choice.reason,target:choice.winner.id,improvementPct:choice.improvementPct};if(s.optimization.autoApply&&Date.now()-this.lastDecisionAt>30*60_000){this.lastDecisionAt=Date.now();await this.applyProfile(choice.winner.id);}}}
    this.onEvent('supreme-mind',this.status());return this.status();}
}
module.exports={SupremeMind};
