'use strict';

const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const {ROOT,getSettings,saveSettings,validWallet,writeJsonAtomic,RUNTIME_DIR}=require('./config');
const {Store}=require('../database/store');const {XmrigController,CONFIG_GEN,CONFIG_SAFE,CONFIG_USER,LOG}=require('../miner/xmrig-controller');
const {HardwareProvider}=require('../providers/hardware');const {PowerProvider}=require('../providers/power');const {MarketDataProvider}=require('../providers/market');
const {MoneroOceanAdapter}=require('../providers/moneroocean');const {P2PoolAdapter}=require('../providers/p2pool');
const Stats=require('../optimizer/statistics');const Profit=require('../optimizer/profit-engine');const Anomaly=require('../optimizer/anomaly');
const {BenchmarkEngine}=require('../optimizer/benchmark-engine');const {SupremeMind}=require('../optimizer/supreme-mind');

const VERSION='5.0.0';const HOST=process.env.HOST||'127.0.0.1';const PORT=Number(process.env.PORT||8080);const FRONTEND=path.join(ROOT,'frontend','index.html');
const store=new Store();const hardwareProvider=new HardwareProvider();const marketProvider=new MarketDataProvider();const powerProvider=new PowerProvider(getSettings);
const WORKER_SECRET=process.env.WORKER_SHARED_SECRET||'';
const clients=new Set();function emit(type,data){const payload=`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`;for(const res of [...clients]){try{res.write(payload);}catch{clients.delete(res);}}}
const miner=new XmrigController({settingsProvider:getSettings,store,onEvent:emit});
const mo=new MoneroOceanAdapter(getSettings),p2p=new P2PoolAdapter(getSettings);function poolAdapter(){return getSettings().pool.adapter==='p2pool'?p2p:mo;}
const benchmark=new BenchmarkEngine({miner,store,settingsProvider:getSettings,saveSettings,powerProvider,hardwareProvider,marketProvider,poolAdapter:mo,onEvent:emit});
const supreme=new SupremeMind({store,settingsProvider:getSettings,saveSettings,miner,onEvent:emit});

let statusCache=null,statusAt=0,refreshPromise=null,lastPoolSnapshot=0,lastMarketSnapshot=0,lastSupremeEval=0;
function maskWallet(v){const s=String(v||'');return s.length>22?`${s.slice(0,10)}…${s.slice(-10)}`:s;}
function isLoopback(req){return ['127.0.0.1','::1','::ffff:127.0.0.1'].includes(String(req.socket.remoteAddress||''));}
function requireLocal(req){if(!isLoopback(req))throw Object.assign(new Error('Controle permitido apenas localmente.'),{status:403});}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','content-security-policy':"default-src 'none'; frame-ancestors 'none'"});res.end(body);}
async function body(req){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>1024*1024)throw Object.assign(new Error('Payload grande demais.'),{status:413});chunks.push(c);}if(!chunks.length)return {};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw Object.assign(new Error('JSON inválido.'),{status:400});}}
function rangeMs(v){return ({'15m':15*60e3,'1h':3600e3,'6h':6*3600e3,'24h':24*3600e3,'7d':7*24*3600e3,'30d':30*24*3600e3})[v]||3600e3;}
function chooseIncrement(xmrPerHour,sessionReal=0){if(!(xmrPerHour>0))return null;const target=xmrPerHour*.25;const quanta=[1e-8,5e-8,1e-7,5e-7,1e-6,5e-6,1e-5,5e-5,1e-4,5e-4,1e-3];let q=quanta[0];for(const x of quanta){q=x;if(x>=target)break;}const progress=sessionReal>0?sessionReal%q:0;return {quantityXmr:q,progressXmr:progress,remainingXmr:Math.max(0,q-progress)};}
function rateEstimate({session,pool,network,miner,workers}){const sources=[];let sum=0,w=0;const elapsedH=session?.started_at?(Date.now()-session.started_at)/3600e3:0;const currentTotal=(Number(pool?.dueXmr)||0)+(Number(pool?.paidXmr)||0);const observed=session&&pool?.status==='real'?Math.max(0,currentTotal-Number(session.starting_pool_total||0)):0;if(observed>0&&elapsedH>.05){const r=observed/elapsedH,c=Math.min(.95,.35+Math.log1p(elapsedH*4)*.2);sources.push({id:'pool-balance-growth',rate:r,weight:.9,confidence:c,type:'observed'});sum+=r*.9;w+=.9;}
  if(network?.status==='real'&&pool?.fresh&&pool.hashrate>0){const r=Profit.networkXmrPerHour(pool.hashrate,network.difficulty,network.reward,1,.99);sources.push({id:'pool-normalized-hash',rate:r,weight:.75,confidence:.72,type:'model'});sum+=r*.75;w+=.75;}
  const fallbackHash=Number(miner.localHash||0)+Number(workers?.hashrate||0);if(network?.status==='real'&&fallbackHash>0){const r=Profit.networkXmrPerHour(fallbackHash,network.difficulty,network.reward,1,.99);sources.push({id:'local-randomx-network-model',rate:r,weight:.45,confidence:.48,type:'model'});sum+=r*.45;w+=.45;}
  const rate=w?sum/w:0;const conf=w?sources.reduce((s,x)=>s+x.confidence*x.weight,0)/w:0;return {available:rate>0,xmrPerHour:rate,confidence:Math.max(0,Math.min(1,conf)),sources,observedSessionXmr:observed};}
function shareIntervals(){const rows=store.poolSnapshots(6*3600e3,2000),ts=[];for(const r of rows){const x=Number(r.last_share_ts||0);if(x&&x!==ts.at(-1))ts.push(x>1e12?x/1000:x);}const intervals=[];for(let i=1;i<ts.length;i++){const d=ts[i]-ts[i-1];if(d>0&&d<6*3600)intervals.push(d);}return intervals;}
function verifyWorker(req,raw){
  if(!WORKER_SECRET||WORKER_SECRET==='troque-por-um-segredo-forte')return false;
  const ts=String(req.headers['x-ideagold-timestamp']||''),sig=String(req.headers['x-ideagold-signature']||'');
  if(!/^\d{10,16}$/.test(ts)||!/^[a-f0-9]{64}$/i.test(sig)||Math.abs(Date.now()-Number(ts))>300000)return false;
  const expected=crypto.createHmac('sha256',WORKER_SECRET).update(ts).update('.').update(raw).digest('hex');
  try{return crypto.timingSafeEqual(Buffer.from(sig,'hex'),Buffer.from(expected,'hex'));}catch{return false;}
}
function healthScore({miner:m,hardware:hw,accepted=0,rejected=0}={}){
  let score=100; const factors=[]; const penalize=(points,reason)=>{score-=points;factors.push({points:-points,reason});};
  if(m?.processRunning&&!(m.localHash>0))penalize(25,'processo aberto sem hashrate');
  if(m?.hugePagesPct===0)penalize(20,'Huge Pages 0%'); else if(m?.hugePagesPct!=null&&m.hugePagesPct<90)penalize(10,'Huge Pages parcial');
  if(m?.msr==='error')penalize(20,'MSR falhou');
  const shares=accepted+rejected;if(shares>=5&&rejected/shares>=.05)penalize(25,'rejeição de shares >= 5%');
  if(hw?.cpuTemperatureC!=null){const t=Number(hw.cpuTemperatureC),cfg=getSettings().thermal;if(t>=cfg.criticalC)penalize(50,'temperatura crítica');else if(t>=cfg.warningC)penalize(15,'temperatura de aviso');}
  if(m?.source==='none'&&m?.processRunning)penalize(15,'telemetria XMRig indisponível');
  return {score:Math.max(0,Math.min(100,score)),factors,status:score>=90?'excellent':score>=75?'good':score>=55?'attention':'critical'};
}
function sessionAggregate(id){if(!id)return null;const rows=store.sessionTelemetry(id,20000);if(!rows.length)return null;const h=Stats.robust(rows.map(r=>Number(r.local_hash)).filter(x=>x>0)),p=Stats.robust(rows.map(r=>Number(r.power_watts)).filter(x=>x>0)),prices=Stats.robust(rows.map(r=>Number(r.xmr_price_brl)).filter(x=>x>0));let kwh=0;for(let i=1;i<rows.length;i++){const dt=Math.max(0,Math.min(60,(rows[i].ts-rows[i-1].ts)/1000));kwh+=(Number(rows[i-1].power_watts)||0)/1000*dt/3600;}return {avgHash:h.mean,hashMedian:h.median,hashCv:h.cv,avgPower:p.mean,avgPrice:prices.mean,energyKwh:kwh,samples:rows.length};}
async function refreshStatus(force=false){if(!force&&statusCache&&Date.now()-statusAt<3500)return statusCache;if(refreshPromise)return refreshPromise;refreshPromise=(async()=>{const settings=getSettings(),adapter=poolAdapter(),workers=store.workerSummary();const [m,pool,network,market]=await Promise.all([miner.telemetry(),adapter.status(),mo.network(),marketProvider.get()]);const hw=hardwareProvider.status(),power=powerProvider.read({mining:m.state==='mining'||m.state==='initializing',gpuActive:m.gpuActive});const sess=store.session(m.sessionId);const rate=rateEstimate({session:sess,pool,network,miner:m,workers});const acceptedSession=pool?.accepted!=null&&sess?Math.max(0,Number(pool.accepted)-Number(sess.starting_accepted||0)):m.accepted;const rejectedSession=pool?.rejected!=null&&sess?Math.max(0,Number(pool.rejected)-Number(sess.starting_rejected||0)):m.rejected;const share=Stats.shareEta(m.localHash,m.shareDifficulty,shareIntervals());const inc=chooseIncrement(rate.xmrPerHour,rate.observedSessionXmr);let eta={available:false};if(inc&&inc.remainingXmr>0&&rate.xmrPerHour>0){const meanSec=inc.remainingXmr/(rate.xmrPerHour/3600);const spread=Math.max(.15,1-rate.confidence);eta={available:true,quantityXmr:inc.quantityXmr,remainingXmr:inc.remainingXmr,meanSec,optimisticSec:meanSec*Math.max(.45,1-spread*.45),conservativeSec:meanSec*(1+spread*1.25),confidence:rate.confidence,note:'ETA estatística de produção esperada; o crédito do pool pode chegar em blocos.'};}
    const profitability=rate.available&&market.brl?Profit.calculate({xmrPerHour:rate.xmrPerHour,priceBrl:market.brl,watts:power.watts,idleWatts:power.idleWatts,costMode:power.costMode,tariff:settings.electricityBrlKwh,hashrate:m.localHash,cloudCostBrlDay:Number(workers.energyCostBrlDay||0)+Number(workers.cloudCostBrlDay||0)}):null;const hist=store.history(60*60e3,360);const anomalies=Anomaly.evaluate({localHash:m.localHash,powerWatts:power.watts,cpuTemp:hw.cpuTemperatureC,rejectRate:(acceptedSession+rejectedSession)>0?rejectedSession/(acceptedSession+rejectedSession):0},hist);
    const ping=adapter.ping?await adapter.ping().catch(()=>null):null;const poolScore=adapter.score?adapter.score({pool,ping}):null;const health=healthScore({miner:m,hardware:hw,accepted:acceptedSession,rejected:rejectedSession});const now=Date.now();if(pool?.status==='real'&&now-lastPoolSnapshot>20000){store.addPoolSnapshot(pool);lastPoolSnapshot=now;}if(market?.status!=='unavailable'&&now-lastMarketSnapshot>60000){store.addMarketSnapshot(market);lastMarketSnapshot=now;}
    const realState=benchmark.state().running?'autotuning':m.state;const dataQuality={miner:m.source==='xmrig-api'?'real':m.source==='xmrig-log'?'real-log':m.source==='process-only'?'process-only':'unavailable',pool:pool?.status||'unavailable',market:market?.status||'unavailable',power:power.real?'real-user-measured':'estimated',temperature:hw.temperatureSource||'unavailable',profit:profitability?'estimated-from-real-inputs':'unavailable'};
    const out={version:VERSION,at:now,state:realState,configured:validWallet(settings.wallet),walletMasked:maskWallet(settings.wallet),settings:{...settings,wallet:isLoopbackDummy()?settings.wallet:''},miner:m,pool,network,market,hardware:hw,power,session:{id:m.sessionId,startedAt:m.startedAt,accepted:acceptedSession,rejected:rejectedSession,stale:pool?.stale??null,earnedXmrReal:rate.observedSessionXmr,source:pool?.status==='real'?'pool-balance-delta':'unavailable'},rate,eta,shareEta:share,profit:profitability?{...profitability,rows:Profit.rows(profitability),scenarios:Profit.scenarios({xmrPerHour:rate.xmrPerHour,priceBrl:market.brl,watts:power.watts,idleWatts:power.idleWatts,costMode:power.costMode,tariff:settings.electricityBrlKwh,hashrate:m.localHash,difficulty:network?.difficulty,cloudCostBrlDay:Number(workers.energyCostBrlDay||0)+Number(workers.cloudCostBrlDay||0)}).out}:null,benchmark:benchmark.state(),supremeMind:supreme.status(),workers,poolScore,poolPing:ping,health,anomalies,dataQuality};
    statusCache=out;statusAt=Date.now();return out;})().finally(()=>{refreshPromise=null;});return refreshPromise;}
function isLoopbackDummy(){return true;}
async function recordTelemetry(){try{const s=await refreshStatus(true);store.addTelemetry({ts:s.at,sessionId:s.session.id,localHash:s.miner.localHash,hash10s:s.miner.hash10s,hash60s:s.miner.hash60s,hash15m:s.miner.hash15m,poolHash:s.pool?.hashrate||0,accepted:s.session.accepted,rejected:s.session.rejected,stale:s.session.stale,cpuLoad:s.hardware.cpuLoad,memoryLoad:s.hardware.memoryLoad,cpuTemp:s.hardware.cpuTemperatureC,gpuTemp:s.hardware.gpuTemperatureC,powerWatts:s.power.watts,powerSource:s.power.source,xmrPriceBrl:s.market?.brl,xmrDue:s.pool?.dueXmr,xmrSession:s.session.earnedXmrReal,xmrPerHour:s.rate.xmrPerHour,profitDayBrl:s.profit?.netDayBrl,minerState:s.state,poolState:s.pool?.status,algo:s.miner.algo,profileId:null});emit('status',s);if(Date.now()-lastSupremeEval>60000){lastSupremeEval=Date.now();supreme.evaluate(s).catch(e=>store.log('optimization','warn','Supreme Mind avaliação falhou',{error:e.message}));}if(getSettings().thermal.autoPauseCritical&&s.hardware.cpuTemperatureC!=null&&s.hardware.cpuTemperatureC>=getSettings().thermal.criticalC&&s.miner.processRunning&&!s.miner.paused){miner.pause();store.decision({source:'safety',action:'thermal-pause',reason:`Temperatura ${s.hardware.cpuTemperatureC} C >= limite crítico`,confidence:1});}}catch(e){store.log('error','warn','Falha no ciclo de telemetria',{error:e.message});}}
function finalizeSession(id,current,reason){const sess=store.session(id);if(!sess)return;const a=sessionAggregate(id)||{},total=(Number(current?.pool?.dueXmr)||0)+(Number(current?.pool?.paidXmr)||0),observed=Math.max(0,total-Number(sess.starting_pool_total||0));const cost=a.energyKwh*getSettings().electricityBrlKwh,gross=observed*(a.avgPrice||Number(current?.market?.brl)||0);store.endSession(id,{stoppedAt:Date.now(),endingPoolTotal:total,accepted:current?.session?.accepted||0,rejected:current?.session?.rejected||0,avgHash:a.avgHash,avgPower:a.avgPower,energyKwh:a.energyKwh,energyCostBrl:cost,xmrObserved:observed,avgXmrPriceBrl:a.avgPrice,estimatedProfitBrl:gross-cost,stopReason:reason});}

async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&['/','/index.html','/styles.css','/app.js'].includes(u.pathname)){const map={'/':FRONTEND,'/index.html':FRONTEND,'/styles.css':path.join(ROOT,'frontend','styles.css'),'/app.js':path.join(ROOT,'frontend','app.js')};const file=map[u.pathname];if(!fs.existsSync(file))return json(res,404,{error:'Arquivo estático ausente.'});const data=fs.readFileSync(file),type=u.pathname.endsWith('.css')?'text/css; charset=utf-8':u.pathname.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8';res.writeHead(200,{'content-type':type,'content-length':data.length,'cache-control':u.pathname==='/'||u.pathname.endsWith('.html')?'no-cache':'public, max-age=60','x-content-type-options':'nosniff','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'"});return res.end(data);}if(req.method==='GET'&&u.pathname==='/api/events'){res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive','x-accel-buffering':'no'});res.write(`event: hello\ndata: ${JSON.stringify({version:VERSION})}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res));return;}
  if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,name:'IdeaGold',version:VERSION,time:new Date().toISOString(),db:'sqlite',host:HOST});
  if(req.method==='GET'&&(u.pathname==='/api/status'||u.pathname==='/api/simple/status'))return json(res,200,await refreshStatus());
  if(req.method==='GET'&&u.pathname==='/api/hardware')return json(res,200,hardwareProvider.status());
  if(req.method==='GET'&&u.pathname==='/api/pool')return json(res,200,{selected:getSettings().pool.adapter,current:await poolAdapter().status(),moneroocean:await mo.status(),p2pool:await p2p.status()});
  if(req.method==='GET'&&u.pathname==='/api/workers'){requireLocal(req);return json(res,200,store.workerSummary());}
  if(req.method==='GET'&&u.pathname==='/api/settings'){requireLocal(req);return json(res,200,getSettings());}
  if(req.method==='GET'&&u.pathname==='/api/history')return json(res,200,{range:u.searchParams.get('range')||'1h',rows:store.history(rangeMs(u.searchParams.get('range')||'1h'),4000)});
  if(req.method==='GET'&&u.pathname==='/api/sessions')return json(res,200,store.sessions(Number(u.searchParams.get('limit')||50)));
  if(req.method==='GET'&&u.pathname==='/api/benchmarks')return json(res,200,{state:benchmark.state(),rows:store.benchmarks(getSettings().fingerprint,200)});
  if(req.method==='GET'&&u.pathname==='/api/profiles')return json(res,200,store.profiles(getSettings().fingerprint));
  if(req.method==='GET'&&u.pathname==='/api/profiles/export'){requireLocal(req);const p=store.profile(String(u.searchParams.get('id')||''));if(!p||p.fingerprint!==getSettings().fingerprint)return json(res,404,{error:'Perfil não encontrado.'});return json(res,200,{schema:'ideagold-profile-v1',name:p.name,kind:p.kind,config:p.config,metrics:p.metrics,fingerprint:p.fingerprint,exportedAt:new Date().toISOString()});}
  if(req.method==='GET'&&u.pathname==='/api/supreme-mind')return json(res,200,supreme.status());
  if(req.method==='GET'&&u.pathname==='/api/logs'){const type=u.searchParams.get('type')||'all';if(type==='xmrig')return json(res,200,{type:'xmrig',source:LOG,text:miner.readLog(250000)});return json(res,200,{type,rows:store.logs(type,Number(u.searchParams.get('limit')||300))});}
  if(req.method==='GET'&&u.pathname==='/api/miner/configs'){requireLocal(req);return json(res,200,{generated:fs.existsSync(CONFIG_GEN),safe:fs.existsSync(CONFIG_SAFE),user:fs.existsSync(CONFIG_USER),paths:{generated:CONFIG_GEN,safe:CONFIG_SAFE,user:CONFIG_USER}});}
  if(req.method==='POST'&&u.pathname==='/api/workers/heartbeat'){
    const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>1024*1024)return json(res,413,{error:'Payload grande demais.'});chunks.push(c);}const raw=Buffer.concat(chunks);
    if(!verifyWorker(req,raw))return json(res,401,{error:'Assinatura de worker inválida.'});let w;try{w=JSON.parse(raw.toString('utf8'));}catch{return json(res,400,{error:'JSON inválido.'});}
    const id=String(w.id||'').slice(0,80);if(!/^[\w.-]+$/.test(id))return json(res,400,{error:'Worker inválido.'});store.upsertWorker({...w,id});emit('workers',store.workerSummary());return json(res,200,{ok:true});
  }
  if(req.method==='POST'){requireLocal(req);const b=await body(req);
    if(u.pathname==='/api/wallet'){const wallet=String(b.wallet||'').trim();if(!validWallet(wallet))throw Object.assign(new Error('Endereço público XMR inválido.'),{status:400});const s=saveSettings({wallet});statusAt=0;return json(res,200,{ok:true,walletMasked:maskWallet(s.wallet)});}
    if(u.pathname==='/api/settings'){const s=saveSettings(b);statusAt=0;store.log('system','info','Configurações atualizadas',{fields:Object.keys(b)});return json(res,200,{ok:true,settings:s});}
    if(u.pathname==='/api/miner/start'||u.pathname==='/api/simple/start'){const pre=await poolAdapter().status();const r=await miner.start();if(r.started){store.startSession({id:r.sessionId,startedAt:Date.now(),pool:getSettings().pool.adapter,walletMasked:maskWallet(getSettings().wallet),mode:getSettings().optimization.mode,startingPoolTotal:(Number(pre?.dueXmr)||0)+(Number(pre?.paidXmr)||0),startingAccepted:Number(pre?.accepted)||0,startingRejected:Number(pre?.rejected)||0});store.log('mining','info','Sessão iniciada',{sessionId:r.sessionId});}statusAt=0;return json(res,200,{ok:true,result:r});}
    if(u.pathname==='/api/miner/stop'||u.pathname==='/api/simple/stop'){const cur=await refreshStatus(true),id=cur.session.id,r=miner.stop('user');finalizeSession(id,cur,'user');statusAt=0;return json(res,200,{ok:true,result:r});}
    if(u.pathname==='/api/miner/pause'){const r=miner.pause();statusAt=0;return json(res,200,{ok:true,result:r});}
    if(u.pathname==='/api/miner/resume'){const r=await miner.resume();statusAt=0;return json(res,200,{ok:true,result:r});}
    if(u.pathname==='/api/miner/restart'||u.pathname==='/api/simple/restart'){const r=await miner.restart();statusAt=0;return json(res,200,{ok:true,result:r});}
    if(u.pathname==='/api/miner/install'){const r=await miner.install();return json(res,200,{ok:true,miner:{version:r.version,verified:r.verified,source:r.source}});}
    if(u.pathname==='/api/miner/config/import'){const r=miner.importUserConfig(b.config||b);return json(res,200,{ok:true,result:r,note:'Config importada; host HTTP, pool/wallet, segurança e backend GPU continuam controlados pelo IdeaGold.'});}
    if(u.pathname==='/api/benchmark/start'||u.pathname==='/api/autotune/start'){const r=await benchmark.start({objective:b.objective});return json(res,202,{ok:true,benchmark:r});}
    if(u.pathname==='/api/benchmark/stop'||u.pathname==='/api/autotune/stop')return json(res,200,{ok:true,result:benchmark.stop()});
    if(u.pathname==='/api/supreme-mind/toggle')return json(res,200,{ok:true,supremeMind:supreme.toggle(Boolean(b.enabled))});
    if(u.pathname==='/api/supreme-mind/mode')return json(res,200,{ok:true,supremeMind:supreme.mode(String(b.mode||''))});
    if(u.pathname==='/api/profiles/apply'){const p=await supreme.applyProfile(String(b.id||''));statusAt=0;return json(res,200,{ok:true,profile:p});}
    if(u.pathname==='/api/profiles/restore-safe'){const p=await supreme.restoreSafe();statusAt=0;return json(res,200,{ok:true,profile:p});}
    if(u.pathname==='/api/profiles/save-current'){const s=getSettings(),id=crypto.randomUUID(),p={id,name:String(b.name||`Perfil ${new Date().toLocaleString('pt-BR')}`).slice(0,80),kind:'custom',fingerprint:s.fingerprint,config:s.mining,metrics:{source:'user-current'},safe:false};store.saveProfile(p);return json(res,200,{ok:true,profile:p});}
    if(u.pathname==='/api/profiles/rename'){const p=store.profile(String(b.id||''));if(!p||p.fingerprint!==getSettings().fingerprint)throw Object.assign(new Error('Perfil não encontrado.'),{status:404});p.name=String(b.name||'').trim().slice(0,80);if(!p.name)throw Object.assign(new Error('Nome inválido.'),{status:400});store.saveProfile(p);return json(res,200,{ok:true,profile:p});}
    if(u.pathname==='/api/profiles/import'){const s=getSettings(),src=b.profile||b;if(src.schema&&src.schema!=='ideagold-profile-v1')throw Object.assign(new Error('Schema de perfil não suportado.'),{status:400});const c=src.config||{};const max=Math.max(1,s.hardware?.coresLogical||require('os').cpus().length);const threads=Math.round(Number(c.threads));if(!(threads>=1&&threads<=max))throw Object.assign(new Error('Threads do perfil incompatíveis.'),{status:400});const config={threads,priority:Math.max(0,Math.min(5,Math.round(Number(c.priority??s.mining.priority)))),yield:Boolean(c.yield)};const p={id:crypto.randomUUID(),name:String(src.name||'Perfil importado').slice(0,80),kind:'imported',fingerprint:s.fingerprint,config,metrics:{...(src.metrics||{}),imported:true},safe:false};store.saveProfile(p);return json(res,200,{ok:true,profile:p,note:'Perfil importado requer benchmark antes de ser considerado seguro.'});}
  }
  return json(res,404,{error:'Rota não encontrada.'});}

const server=http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);store.log('error','error',e.message,{path:req.url});json(res,e.status||500,{error:e.message||'Erro interno.'});}));
setInterval(recordTelemetry,10000).unref();setInterval(()=>miner.recover().catch(e=>store.log('error','warn','Watchdog falhou',{error:e.message})),30000).unref();
process.on('SIGINT',()=>{try{store.close();}catch{}process.exit(0);});process.on('SIGTERM',()=>{try{store.close();}catch{}process.exit(0);});
server.listen(PORT,HOST,()=>{console.log(`\nIdeaGold ${VERSION} — Supreme Mind: http://${HOST}:${PORT}`);console.log('Local-first: controle de mineração aceito apenas via loopback.');store.log('system','info',`IdeaGold ${VERSION} iniciado`,{host:HOST,port:PORT});recordTelemetry();});
