'use strict';
const os=require('os');const {spawnSync}=require('child_process');const {hardwareFingerprint}=require('../backend/config');
class HardwareProvider{
  constructor(){this.cache=null;this.cacheAt=0;this.static=this.detectStatic();}
  detectStatic(){const cpus=os.cpus()||[];let gpus=[];if(process.platform==='win32'){const ps="Get-CimInstance Win32_VideoController | Select-Object Name,AdapterRAM,DriverVersion | ConvertTo-Json -Compress";const r=spawnSync('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-Command',ps],{encoding:'utf8',timeout:4000,windowsHide:true});try{const d=JSON.parse(r.stdout.trim());gpus=(Array.isArray(d)?d:[d]).filter(Boolean).map(x=>({name:String(x.Name||'unknown'),vramGB:Number(x.AdapterRAM)>0?Number((Number(x.AdapterRAM)/1024**3).toFixed(2)):null,driver:String(x.DriverVersion||'')}));}catch{}}return {provider:process.platform==='win32'?'WindowsProvider':'GenericProvider',cpuModel:cpus[0]?.model||'unknown',coresLogical:cpus.length,architecture:os.arch(),memoryTotalGB:Number((os.totalmem()/1024**3).toFixed(2)),gpus,platform:os.platform(),osRelease:os.release(),hostname:os.hostname(),fingerprint:hardwareFingerprint()};}
  windowsDynamic(){const ps=`$ErrorActionPreference='SilentlyContinue'; $cpu=Get-CimInstance Win32_Processor | Select-Object -First 1 LoadPercentage,MaxClockSpeed; $os=Get-CimInstance Win32_OperatingSystem; [pscustomobject]@{cpuLoad=$cpu.LoadPercentage;clockMHz=$cpu.MaxClockSpeed;freeKB=$os.FreePhysicalMemory;totalKB=$os.TotalVisibleMemorySize}|ConvertTo-Json -Compress`;
    const r=spawnSync('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-Command',ps],{encoding:'utf8',timeout:3500,windowsHide:true});if(r.status!==0)return null;try{return JSON.parse(r.stdout.trim());}catch{return null;}}
  dynamic(){if(Date.now()-this.cacheAt<5000&&this.cache)return this.cache;let cpuLoad=null,memoryLoad=null,clockMHz=null;if(process.platform==='win32'){const d=this.windowsDynamic();if(d){cpuLoad=Number(d.cpuLoad);clockMHz=Number(d.clockMHz);const total=Number(d.totalKB),free=Number(d.freeKB);memoryLoad=total>0?(1-free/total)*100:null;}}else{cpuLoad=os.loadavg()[0]/Math.max(1,os.cpus().length)*100;memoryLoad=(1-os.freemem()/os.totalmem())*100;clockMHz=os.cpus()[0]?.speed||null;}
    this.cache={cpuLoad:Number.isFinite(cpuLoad)?cpuLoad:null,memoryLoad:Number.isFinite(memoryLoad)?memoryLoad:null,clockMHz:Number.isFinite(clockMHz)?clockMHz:null,cpuTemperatureC:null,gpuTemperatureC:null,temperatureSource:'unavailable',powerSensorWatts:null,powerSensorSource:'unavailable',at:Date.now()};this.cacheAt=Date.now();return this.cache;}
  status(){return {...this.static,...this.dynamic()};}
}
module.exports={HardwareProvider};
