'use strict';
class MoneroOceanAdapter{
  constructor(settingsProvider){this.settingsProvider=settingsProvider;this.id='moneroocean';this.name='MoneroOcean';this.feePct=0;}
  async fetchJson(url){const r=await fetch(url,{headers:{accept:'application/json','user-agent':'IdeaGold/5.0'},signal:AbortSignal.timeout(6000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
  mapMiner(d){if(!d)return null;const n=(...ks)=>{for(const k of ks)if(d[k]!=null)return Number(d[k])||0;return 0;};const last=n('lastHash','lastShare','lts','last');return {adapter:this.id,dueXmr:n('amtDue','due','balance')/1e12,paidXmr:n('amtPaid','paid')/1e12,hashrate:n('hash2','hash','hashrate'),rawHashrate:n('hash','hashrate'),accepted:n('validShares','valid','vs'),rejected:n('invalidShares','invalid','is'),stale:null,totalHashes:n('totalHashes','totalHash','th'),lastShareTs:last,lastAlgo:String(d.la||d.lastShareAlgo||''),workers:null,minimumPayoutXmr:null,raw:d};}
  fresh(p){if(!p?.lastShareTs)return false;const ts=p.lastShareTs>1e12?p.lastShareTs/1000:p.lastShareTs;return Date.now()/1000-ts<=15*60;}
  async status(){const s=this.settingsProvider();if(!s.wallet)return {adapter:this.id,status:'unconfigured',fresh:false};try{const p=this.mapMiner(await this.fetchJson(`https://api.moneroocean.stream/miner/${encodeURIComponent(s.wallet)}/stats`));let workers=[];try{workers=await this.fetchJson(`https://api.moneroocean.stream/miner/${encodeURIComponent(s.wallet)}/allWorkers`);}catch{};p.workers=Array.isArray(workers)?workers.length:(workers&&typeof workers==='object'?Object.keys(workers).length:null);p.fresh=this.fresh(p);p.status=p.fresh?'real':'stale';return p;}catch(error){return {adapter:this.id,status:'api-disconnected',fresh:false,error:error.message};}}
  async network(){try{const d=await this.fetchJson('https://api.moneroocean.stream/network/stats');let reward=Number(d.value||0);if(reward>1e6)reward/=1e12;const difficulty=Number(d.difficulty||0);if(!(difficulty>0&&reward>0&&reward<10))throw new Error('invalid network data');return {status:'real',difficulty,reward,height:Number(d.height||d.main_height||0),networkHashrate:Number(d.hash||d.hashrate||0)||null,source:'MoneroOcean network/stats',at:Date.now()};}catch(error){return {status:'api-disconnected',error:error.message};}}
  async ping(){const s=this.settingsProvider();const start=Date.now();try{await this.fetchJson('https://api.moneroocean.stream/network/stats');return {status:'real',ms:Date.now()-start,endpoint:s.pool?.host||'gulf.moneroocean.stream'};}catch(error){return {status:'unavailable',ms:null,error:error.message};}}
  score({pool,ping}={}){let score=50,reasons=[];if(pool?.fresh){score+=20;reasons.push('shares recentes');}else reasons.push('sem share recente');if(Number(pool?.rejected)===0){score+=10;reasons.push('sem rejects observados');}if(ping?.ms!=null){if(ping.ms<250)score+=10;else if(ping.ms>1000)score-=10;reasons.push(`API ${ping.ms} ms`);}if(this.feePct===0){score+=5;reasons.push('adapter sem taxa declarada no cálculo');}return {score:Math.max(0,Math.min(100,score)),reasons,dataCompleteness:pool?.status==='real'?.8:.35};}
}
module.exports={MoneroOceanAdapter};
