'use strict';
const fs=require('fs');const path=require('path');const net=require('net');const {spawnSync}=require('child_process');
class P2PoolAdapter{
  constructor(settingsProvider){this.settingsProvider=settingsProvider;this.id='p2pool';this.name='P2Pool';this.feePct=0;}
  detect(){const candidates=[];if(process.env.P2POOL_EXE)candidates.push(process.env.P2POOL_EXE);if(process.platform==='win32')candidates.push(path.join(process.env.USERPROFILE||'','bin','p2pool.exe'),path.join(process.cwd(),'p2pool.exe'));else candidates.push('/usr/local/bin/p2pool','/usr/bin/p2pool',path.join(process.cwd(),'p2pool'));const exe=candidates.find(x=>x&&fs.existsSync(x))||null;let version=null;if(exe){const r=spawnSync(exe,['--version'],{encoding:'utf8',timeout:3000,windowsHide:true});version=String(r.stdout||r.stderr||'').trim().split(/\r?\n/)[0]||null;}return {installed:Boolean(exe),exe,version,sidechains:['main','mini','nano'],status:exe?'detected':'not-installed'};}
  probe(host,port){return new Promise(resolve=>{const start=Date.now(),s=net.createConnection({host,port});const done=(ok,error)=>{try{s.destroy()}catch{}resolve({ok,ms:ok?Date.now()-start:null,error:error?.message||null})};s.setTimeout(1500);s.once('connect',()=>done(true));s.once('timeout',()=>done(false,new Error('timeout')));s.once('error',e=>done(false,e));});}
  async status(){const d=this.detect(),cfg=this.settingsProvider().pool||{},host=cfg.host||'127.0.0.1',port=Number(cfg.port||3333),probe=await this.probe(host,port);return {adapter:this.id,status:probe.ok?'stratum-ready':d.installed?'node-detected-stratum-offline':'not-installed',fresh:probe.ok,hashrate:null,dueXmr:null,paidXmr:null,accepted:null,rejected:null,lastShareTs:null,capability:d,endpoint:`${host}:${port}`,probe,note:probe.ok?'Stratum local respondeu. Saldo/payout P2Pool não é inventado; consulte sua carteira/nó.':'P2Pool é opcional. IdeaGold só minera nele quando o endpoint Stratum local está ativo.'};}
  async network(){return {status:'unavailable',reason:'O adapter não expõe dados de rede sem um endpoint local de API validado.'};}
  async ping(){const cfg=this.settingsProvider().pool||{};const p=await this.probe(cfg.host||'127.0.0.1',Number(cfg.port||3333));return {status:p.ok?'real':'unavailable',ms:p.ms,error:p.error};}
  score({pool}={}){const ready=pool?.status==='stratum-ready';return {score:ready?75:0,reasons:[ready?'Stratum local acessível':'Stratum local indisponível','P2Pool: 0% fee no protocolo; payouts diretos à carteira quando nó está configurado'],dataCompleteness:ready?.35:0};}
}
module.exports={P2PoolAdapter};
